---
name: "Golang"

on: pull_request

jobs:
  golang_linting:
    name: Linting Golang Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'

      - name: Download module dependencies
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go mod download

      - name: Run go fmt
        run: make fmt

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7

      - name: Run go tests
        run: make test
