---
name: "Golang"

on: pull_request

jobs:
  golang_linting:
    name: Linting Golang Code
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.15

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download module dependencies
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go mod download

      - name: Run go fmt
        run: make fmt

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.4.0
        with:
          version: v1.33.0
          args: --enable scopelint,bodyclose,gofmt,golint --exclude-use-default=false --modules-download-mode=vendor --build-tags integration

      - name: Run go tests
        run: make test
