---
name: "New Version Release"
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Produce release body
        id: git_log
        uses: beatlabs/release-changelog-action@190ae359c27547fd0bcedcbe971f8b0364f1b72c
        with:
          tag_regex: "v[0-9]+.[0-9]+.[0-9]+"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.git_log.outputs.release_body }}
          draft: false
          prerelease: false
